version: "3.8"

services:
  mongodb:
    image: mongo
    volumes:
      - mongodbdata:/data/db
    env_file:
      - ./env/mongo.env
    container_name: mongodb # xác định tên container
  backend:
    image: duynguyenquoc/backend-todo-app:latest
    ports:
      - 8000:8000
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
    container_name: backend
  frontend:
    stdin_open: true
    tty: true

    image: duynguyenquoc/frontend-todo-app:latest
    ports:
      - 8081:3000
    container_name: frontend
volumes:
  mongodbdata:
